# Generated by Django 2.0.3 on 2018-04-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, help_text='This field is used to determine if a category is active.', verbose_name='Active'),
        ),
    ]
