# Generated by Django 2.0.3 on 2018-04-13 20:58

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('koff', '0002_auto_20180403_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This field is used for naming the business entity.', max_length=50, verbose_name='Business Entity name')),
                ('active', models.BooleanField(default=True, help_text='This field is used to determine if a business entity is active.', verbose_name='Active')),
                ('address', models.CharField(max_length=50, verbose_name='Business Entity address')),
                ('e_mail', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=50), size=None)),
                ('web_site', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
            ],
            options={
                'verbose_name': 'Business Entity',
                'verbose_name_plural': 'Business Entities',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50, verbose_name='Comment for the entity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koff.BusinessEntity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntityCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EntitySocialReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koff.BusinessEntity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityTelephoneReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koff.BusinessEntity')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koff.BusinessEntity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TelephoneReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='This field is used for short naming the day of the week.', max_length=3, verbose_name='Short day name')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('business_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koff.BusinessEntity')),
            ],
            options={
                'verbose_name': 'Working hours',
                'verbose_name_plural': 'Working hours',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='category',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='category',
            name='path',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koff.Category'),
        ),
        migrations.AddField(
            model_name='entitytelephonereference',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koff.TelephoneReference'),
        ),
        migrations.AddField(
            model_name='entitysocialreference',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koff.SocialReference'),
        ),
        migrations.AddField(
            model_name='entitycategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koff.Category'),
        ),
        migrations.AddField(
            model_name='entitycategories',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koff.BusinessEntity'),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='social_references',
            field=models.ManyToManyField(through='koff.EntitySocialReference', to='koff.SocialReference'),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='telephone_references',
            field=models.ManyToManyField(through='koff.EntityTelephoneReference', to='koff.TelephoneReference'),
        ),
        migrations.AddField(
            model_name='category',
            name='entities',
            field=models.ManyToManyField(through='koff.EntityCategories', to='koff.BusinessEntity'),
        ),
    ]
