# Generated by Django 2.0.3 on 2018-04-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koff', '0004_auto_20180414_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent',
        ),
    ]
