# Generated by Django 2.0.3 on 2018-04-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koff', '0005_auto_20180414_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='entities',
        ),
        migrations.AddField(
            model_name='businessentity',
            name='categories',
            field=models.ManyToManyField(through='koff.EntityCategories', to='koff.Category'),
        ),
    ]
