# Generated by Django 2.0.3 on 2018-05-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koff', '0005_auto_20180518_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500, verbose_name='Comment for the entity'),
        ),
    ]
