# Generated by Django 2.0.3 on 2018-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koff', '0006_auto_20180414_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category_images/no_image.jpg', upload_to='category_images/'),
        ),
    ]
