# Generated by Django 2.0.3 on 2018-04-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koff', '0006_auto_20180414_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, help_text='This field is used for picking the icon in app.', max_length=50, null=True, verbose_name='Icon name'),
        ),
    ]
