# Generated by Django 2.0.3 on 2018-04-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koff', '0007_category_icon_name'),
        ('koff', '0007_category_image'),
    ]

    operations = [
    ]
