# Generated by Django 2.0.3 on 2018-05-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koff', '0007_auto_20180518_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingandcomment',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=5),
        ),
    ]
