# Generated by Django 2.0.3 on 2018-05-31 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koff', '0008_auto_20180530_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitytelephonereference',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entitytelephonereference',
            name='reference',
        ),
        migrations.AlterField(
            model_name='businessentity',
            name='e_mail',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=50), null=True, size=None),
        ),
        migrations.RemoveField(
            model_name='businessentity',
            name='telephone_references',
        ),
        migrations.AddField(
            model_name='businessentity',
            name='telephone_references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='businessentity',
            name='web_site',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), null=True, size=None),
        ),
        migrations.DeleteModel(
            name='EntityTelephoneReference',
        ),
        migrations.DeleteModel(
            name='TelephoneReference',
        ),
    ]
