# Generated by Django 2.0.3 on 2018-05-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koff', '0009_auto_20180531_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessentity',
            old_name='telephone_references',
            new_name='telephone_numbers',
        ),
    ]
