# Generated by Django 2.0.3 on 2018-05-31 14:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koff', '0010_auto_20180531_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessentity',
            name='e_mail',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=50, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='businessentity',
            name='telephone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='businessentity',
            name='web_site',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), null=True, size=None),
        ),
    ]
